//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiData2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetEmployee
    {
        public int employee_id { get; set; }
        [Required(ErrorMessage = "First Name is Must")]
        public string first_name { get; set; }
        [Required(ErrorMessage = "Last Name is Must")]
        public string last_name { get; set; }
        [Required(ErrorMessage = "Email is Must")]
        public string email { get; set; }
        [Required(ErrorMessage = "Phone Number is Must")]
        public string phone_number { get; set; }
        [Required(ErrorMessage = "Hire Date is Must")]
        public System.DateTime hire_date { get; set; }
        public int job_id { get; set; }

        [Required(ErrorMessage = "Salary is Must")]
        public decimal salary { get; set; }
        public Nullable<int> manager_id { get; set; }
        public Nullable<int> department_id { get; set; }
    }
}
