//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiData2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetJob
    {
        public int job_id { get; set; }
        public string job_title { get; set; }
        public Nullable<decimal> min_salary { get; set; }
        public Nullable<decimal> max_salary { get; set; }
    }
}
